const CSVParserState = {
    INITIALIZED: 10,
    PARSING_HEADERS: 20,
    PARSING_HEADERS_COMMENT: 30,
    PARSING_HEADERS_ROW: 40,
    PARSING_COMMENT: 50,
    PARSING_ROW: 60,
    PARSING_ROW_COMMENTS: 70,
    PARSING_ROW_VALUES: 80,
    PARSING_ROW_DOUBLE_QUOTED_VALUE: 90,
    PARSING_VALUE: 100,
    PARSING_ESCAPED: 110,
    SKIPPING_ROWS: 1000,
    SKIPPING_ROW: 1010
}

module.exports = CSVParserState;