const CSVReaderState = {
    INITIALIZED: 10,
    PARSING_END_OF_FILE: 20,
    PARSING_COLUMN: 30,
    PARSING_ROW_DONE: 40,
    PARSING_DOUBLE_QUOTED_COLUMN: 50,
    PARSING_DELIMITER: 60,
    PARSING_NEW_LINE: 70,
    PARSING_WHITESPACE: 80,
    PARSING_CHARACTER: 90,
    PARSING_CHARACTER_WHITESPACE: 100,
    PARSING_CR: 110
}

module.exports = CSVReaderState;